language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - ./vendor/bin/parallel-lint -e php,phpt --exclude ./vendor .

script: ./vendor/bin/tester -c ./tests/php.ini-unix ./tests/CacheFactoryTests

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'

cache:
  directories:
    - $HOME/.composer/cache
